### ISSUE TITLE
Refine the interaction

### ISSUE THREAD

**Issue by Strilanc** [kunalq/testrepo#44]
The interaction with the bot feels really rough right now. It permanently pegs the status of the commit at "running checks". It asks *you* to wait for the tests to pass before merging, instead of waiting on your behalf. It jumps in with "it looks like you're trying to merge!", even though the actual trigger is the PR being approved.

Here's what I'm picturing as the interaction...

- PR gets approved

- "Changes approved. I can **[handle the merge](http://example.com)**."

- User clicks link. User picks message and clicks merge.

- "Merge scheduled. Syncing with master and waiting for tests to pass. You can **[abort the merge](http://example.com)**. [preview of commit message]"

- PR was out of sync with master. Bot syncs with master. Tests start to run. Tests fail.

- "Tests failed. Merge failed. **[Retry the merge](http://example.com)** after fixing."

- Commit added, tests pass, user clicks "retry the merge".

- "Merge rescheduled. Syncing with master waiting for tests to pass. You can **[abort the merge](http://example.com)**. [preview of commit message]"

- Tests have already passed, no need to sync with master, but a minimum ~30 seconds of delay applies so people can abort.

- User sees mistake in message, aborts merge by clicking abort lint.

- "Merge aborted. I can **[handle the merge](http://example.com)** when you do want to merge again."

- User clicks "handle the merge", fixes the message, hits merge.

- "Merge Scheduled. Syncing with master waiting for tests to pass. You can **[abort the merge](http://example.com)**. [preview of commit message]"

- (30 seconds later)

- PR gets merged.

**Comment by kunalq** [comment]
Moved to the main repo.
